server:
  port: 8080

  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:kudlimath_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: kudlimath
    password: Shree@1008
  thymeleaf:
    check-template-location: true
    
    
---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always   

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: incarnationpath@gmail.com
    password: pvldzhtjdgcpwzcp        
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  jhipster:
    mail: # specific JHipster mail property, for standard properties see MailProperties
    from: incarnationpath@gmail.com
    base-url: http://127.0.0.1:8080
---

app:
  const:
    merchantId : 317157
    returnURL : https://www.kudlimath.in/api/v1/donation/response
    redirectURL : https://www.kudlimath.in
    authEncryptionKey : A4476C2062FFA58980DC8F79EB6A799E
    authDecryptionKey : 75AEF0FA1B94B3C10D4F5B268F757F11
    

  