server:
  port: 8080

  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:kudlimath_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: kudlimath
    password: Shree@1008
  thymeleaf:
    check-template-location: true
    
    
---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always   

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kudlimath@gmail.com
    password: vlnp rdgt kenj tgup        
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  jhipster:
    mail: # specific JHipster mail property, for standard properties see MailProperties
    from: incarnationpath@gmail.com
    base-url: http://127.0.0.1:8080
---

app:
  const:
    merchantId : 551670
    #AIPAY_URL : https://paynetzuat.atomtech.in/ots/aipay/auth?
    AIPAY_URL : https://payment1.atomtech.in/ots/aipay/auth?
    returnURL : https://www.kudlimath.in/api/v1/donation/response
    redirectURL : https://www.kudlimath.in
    #returnURL : http://localhost:8080/api/v1/donation/response
    #redirectURL : http://localhost:8080
    authEncryptionKey : 026F40639DF005B044E9525B1221EC01
    authDecryptionKey : 9CEF22EF8B247B977AB14F3CF6151A7C
    signatureRequestHashKey : a10337706d512b2473
---

logging:
  level:
    web: INFO
    org.springframework.web: INFO
    com.sansys: DEBUG
    org.hibernate: ERROR
---

spring:
  output:
    ansi:
      enabled: DETECT
  